services:
  server:
    build:
      context: .
    container_name: server
#    entrypoint: fastapi dev --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - mongo-express
      - redis

  mongodb:
    image: mongo:8.0
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis:latest
    container_name: redis

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongodb
